apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rs-user-api-deployment
  labels:
    app: rs-user-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rs-user-api
    spec:
      containers:
      - name: alpline-linux-golang
        image: gcr.io/real-estate-186513/rs-property-api:v1
        command: ["rs-user-api"]
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: IfNotPresent
        env:
        - name: VERSION
          value: "v1"
        ports:
        - name: http-server
          containerPort: 8080
